### PR TITLE
.tres support

### PR DESCRIPTION
**Pull request by ofrank123**
Adding support for *.tres files using conf-toml-mode, the same as *.tscn files.

### CODE REVIEW

**Comment by NathanLovato** [comment]
I rebased and merged your changes manually. Moving forward, could you use branches to contribute new features? See our guidelines on naming commits here as well: https://www.gdquest.com/docs/guidelines/contributing-to/gdquest-projects/#how-to-create-great-pull-requests

**Comment by NathanLovato** [comment]
Merged manually in c4a5976ebb959d5fc46d0a535f14f7f48e761bbb

**Comment by ofrank123** [comment]
Sure sorry, just added this messily because it was such a small addition.

**Comment by NathanLovato** [comment]
No worries, it's just that when you PR from master, it adds all the commits that differ, including the ones you had already PRed, i.e. tscn file support.

**Comment by NathanLovato** [comment]
Thanks for your contribution, glad someone could bring emacs 26 support! I didn't pay attention to that when using python.el from emacs 27, didn't think it would break compatibility with older emacs versions

**Pull request closed without merging**
