### PR TITLE
Hydra implementation

### PR DESCRIPTION
**Pull request by VlachJosef**
Here is hydra implementation we discussed in #57. This PR also removes work done in #57 as hydra way is much more ergonomic.

### CODE REVIEW

**Comment by NathanLovato** [comment]
How about keeping swiper and ido as fallbacks for people who don't have hydra? I'd think a lot of emacs users would have either helm, swiper, or ido as part of their config, but maybe not hydra.

**Comment by NathanLovato** [comment]
And I forgot but as always, thank you very much for your contribution!

**Comment by VlachJosef** [comment]
You're welcome, but thanks are on my side for everything you are doing 😄 

Ok, I can put prefix argument method back.

**Comment by VlachJosef** [comment]
So now hydra and prefix-argument option work both next to each other and they are completely independent from each other.

**Comment by NathanLovato** [comment]
Thanks much! Looking good, I'll merge now.

**Pull request merged**
